FROM python:3.10-slim

# Set work directory
WORKDIR /app

# Copy the application code
COPY . /app

RUN pip install sqlalchemy alembic python-dotenv psycopg2-binary

CMD ["alembic", "upgrade", "head"]
